---
title: "Schedule for STT 3250 - Spring 2021"
author: "Dr. Lasanthi Watagoda"
date: 'Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")`'
output:
  bookdown::html_document2:
    highlight: textmate
    theme: yeti
    toc: true
    css: "styles.css"
---

***

**Week 1: (Jan 18 -- 22)**

* Go over syllabus
* Chapter 1: Introduction to Probability (1.1)

* [Homework 1: Due Wednesday the 27th](Homework.html)


*Lecture Recordings:*

* [Tuesday's Recording](https://appstate.zoom.us/rec/share/AIE2MMivYN4P4R_BCpz5tehuftkI4TeR6usF-cGC4YFpTwkNKZ8JQ8aPR-qRYZ4.UW_zK8VDC47uNpxB)   
* [Thursday's Recording](https://appstate.zoom.us/rec/share/V0FcxDh1aqGJ4Y2yAdYIsdu14K4DFqxX2hEphljFOj8hWgr2USLssiGteDz4DOCk.HeFGmJvvAK-Fu0lR)

<!--
* [Wednesday's Recording](https://appstate.zoom.us/rec/share/w_B7N7P99jNLHIHW8X3gSoF5AtXOX6a81CUXqfoEzk41Nv3YBZ48tEJGH8h_ZPF-)   
* [Thursday's Recording](https://appstate.zoom.us/rec/share/98pcdqvq-VJLZoHu5EHaCr8iO5_oX6a8h3JL_qdcykbNt_PEDJJ2NiPJoGDJs4n3)  
-->

***

**Week 2: (Jan 25 -- 29)**

* Chapter 1: Introduction to Probability (1.2, 1.3, 1.4)
* In Class Quiz 01 (Thursday, last 20 min of class)

* [Homework 2: Due Wednesday the 03rd](Homework.html)

*Lecture Recordings:*

* [Tuesday's Recording](https://appstate.zoom.us/rec/share/0pXsbYY74dVA9VNO_h-AsEZZwQ6K3wdZsqa1QHXanOgN9QGIviRSOfuWaPpbC6Qw.vyfgYnMQJeKre4AA)
* [Wednesday's Recording](https://appstate.zoom.us/rec/share/FsTGYWTsifNzEY3EFRRvBopYyaCOEhIUdoh2ucutIjrYq3aw-ny6QIzj3QBRy6TN.V9gjNSEuRPrafOak)
* [Thursday's Recording](https://appstate.zoom.us/rec/share/U1nIU7w3Mf8yn6Wmhel9pNgDF5E3dch-gepn-6WyIUEXhnwFUKxlGWFQnRFs82w.tnnDS7_NAaJAy-tl)




<!--



*Office hours Recordings:*

* [Tuesday's Office hours](https://appstate.zoom.us/rec/share/wvYqELLtsWROQ8_G9U_UYI06Eorqaaa8gXAeqPcLxRprar374o_LFKBt6aD-Pr-J) --- HW 1 Help
-->

***

**Week 3: (Feb 01 -- 05)**

* Chapter 1: Introduction to Probability (1.4, 1.5)
* Chapter 2: Discrete Distributions (2.1)
* In Class Quiz 02 (Thursday, last 20 min of class)

* [Homework 3: Due Wednesday the 10th](Homework.html)

*Lecture Recordings:*

* [Tuesday's Recording](https://appstate.zoom.us/rec/share/MRQDkIAKuasyst77cerh6fxwCjwvAgoC20wLL4e7plZHlSmAjqSgrHDRt5-Osf1O.kq7pEtww2P3Wmkr0)
* [Wednesday's Recording](https://appstate.zoom.us/rec/share/FC32yjNY4SlbjwQbzjBMEFPpkaymgohl2LGblk5yJleSNr7KA3S-4N6RxTHfgz3n.nS6kkGMVhCGC_F72)   
* [Thursday's Recording](https://appstate.zoom.us/rec/share/yp8vITnSpNu80ZjoUavVK_Lq49CjwtQZp6LHlsK3knq1XWAqaJ2kZN-ZHY2AFv_1.Cx_rPr4bL_flaxVC)  

<!--
*Office hours Recordings:*

* [Thursday's Office hours](https://appstate.zoom.us/rec/share/XAo_PdlX5_RD0-PjsU_tqzJQIaTqWRENOFcTomIyYCJMEgbglVCFhH7QK1X7sVXJ.0xOhGcErMr82NwkH) --- HW 2 Help
-->

***

**Week 4: (Feb 08 -- 12)**

* Chapter 2: Discrete Distributions (2.2, 2.3)
* In Class Quiz 03 (Thursday, last 20 min of class)
* [Homework 4: Due Wednesday the 17th](Homework.html)

*Lecture Recordings:*

* [Tuesday's Recording](https://appstate.zoom.us/rec/share/wDkBsoYMd_oR5VOHQui7GXxJnh_UIzVfmFqXaVPJpQZ7pn4cmiADPxj2Z9mDu56e.Fr1gisS2ec7zOpZV)
* [Wednesday's Recording](https://appstate.zoom.us/rec/share/Mt5xBZsrNS__cJeWZ3IS4ly7fqPQ0q8Nrs5BwLd2BT5PxICij3i0v48s_qLULkso.wUdLvCx7YG0pOguZ)
* [Thursday's Recording]()

<!--
* [Tuesday's Recording](https://appstate.zoom.us/rec/share/M_kvjs9OjO2e5T4H6FOFrJv0GDWi95OnqP80hOYVUMD9uqcRESJ-zfn9R3oItf52.e-uijmpPs6FwWs7d)
* [Wednesday's Recording](https://appstate.zoom.us/rec/share/8x3kVjV1KTzlz-iNUj3T4sekVbkTmeeGklPWN2NYkR3k8XCfNrQu6hMcq5nILUv_.lO9dN08KaDtHzwDM)
* [Thursday's Recording](https://appstate.zoom.us/rec/share/-a_076-fYt_8QyzUZXYNy7AIqbHMGEBlz_WHawxbwzCpOhSaBhs-KD_EonRcVHnU.0wpewo25MBcG73XH)

*Office hours Recordings:*

* [Thursday's Office hours](https://appstate.zoom.us/rec/share/VTZg_kxt7Ah_hRo6Zdvfb6_Gl4Zf2EBHIP40kYMEVRImvdGTnVSlzACpKXNKiNpI.tKTSnHvPDbS4NeAS) --- HW 3 Help
-->

***

**Week 5: (Feb 15 -- 19)**

* Chapter 2: Discrete Distributions (2.4)
* In Class Quiz 04 (Thursday, last 20 min of class)
* [Homework 5: Due Wednesday the 24th](Homework.html)

*Lecture Recordings:*


* [Tuesday's Recording](https://appstate.zoom.us/rec/share/D1fVYShDBDfBDqSkXiLH0XSJX5v-t0m5q7kG8xGSfcwg2uLbPbLoVUxRa0vOGE1l.wQwbJhMfjwb3oKge)
* [Wednesday's Recording](https://appstate.zoom.us/rec/share/VYTqW7yf4nvyaZt3tIc9er8_hSA10gDNLkvMENbkXgR8GuDNr90ym0OxurK1gmPB.JQtaqfLdmJEF-HBP) 
* [Thursday's Recording](https://appstate.zoom.us/rec/share/aWgVPxHrJbMnjB8eX6tHZsRbxtVjZhpZWufn6C6IFPLX3h0wSbUab-TkPalVlcIA.19ggvhh85THpfBCF)

<!--
*Office hours Recordings:*

* [Thursday's Office hours](https://appstate.zoom.us/rec/share/rClp4p9y5HyNmF4x-m-q8JylIigdeLSOt5kZbN7IE5BErLN0XR7C-noxMZa3MtQm.guWqyZWaGSsbiGfF)
-->

***

**Week 6: (Feb 22 -- 26)**



* Chapter 2: Discrete Distributions (2.5, 2.6)
* [Homework 6: Due Wednesday the 30th](Homework.html)
* In Class Quiz 05 (Thursday, last 20 min of class)

*Lecture Recordings:*

* [Tuesday's Recording](https://appstate.zoom.us/rec/share/mbDYzxnbbEBq7LEfSzb7Bq6ZDazDWhDn2Qs_VbrP8jicE5X3x0hnM0iQ2dLZXPIX.9NWpAOnCCg-tuQkL)
* [Wednesday's Recording](https://appstate.zoom.us/rec/share/oewNBjWHQUT-rX7ZvtylrSMmwZjZpk9i1EgSuuT3l8bhTb6o-U3npsJLJERd6kft.Kr87X2RuSnDR2xJ-) 
* [Thursday's Recording]()


***

**Week 7: (Mar 01 --  05)**

* *Test 01: Thursday the ----- and Covers Ch 1 and 2.*
* Chapter 3: Continuous Distributions (3.1, 3.2)
* [Homework 7: Due Wednesday the 07th](Homework.html)

*Lecture Recordings:*
<!--
* [Tuesday's Recording](https://appstate.zoom.us/rec/share/LTwgKxBZO5eYrzxrRVRfExpq1hFfDwCIWatwrRPW0eAhkzoRwi0ru0yB0KruJZMg.L_AEs0guljbxkTch)
* [Wednesday's Recording](https://appstate.zoom.us/rec/share/pgH_dkoqtmtV9NHiAHwDwku2U0xwjfwpvUCCoIjJx2HC668IJqUIW-VWesz9QMI9.OQoUcAuUT1X5Zidx)
* [Thursday's Recording](https://appstate.zoom.us/rec/share/C7TtTJoGXLYnMRlCMrv7Nwu24ddaQl0_icswBn6W_xtTaXDfKEnnXpMD4n1dkTyJ.zITAA_5qDQPMWvhI)
-->

***

**Week 8: (Mar 08 -- 12)**

* Chapter 3: Continuous Distributions (3.3)
* Chapter 4: Bivariate Distributions (4.1)
* In Class Quiz 06 (Thursday, last 20 min of class)
* [Homework 8: Due Wednesday the 14th](Homework.html)

*Lecture Recordings:*
<!--
* [Tuesday's Recording](https://appstate.zoom.us/rec/share/DdWjzG1eZWN87Wrr6LEEGepeVaZ_JAe9WMESuRK183KniHukTZkdzR3qYffT3IRz.CE5leIEjeYwoLOIJ)
* [Wednesday's Recording](https://appstate.zoom.us/rec/share/XLRuBMlFQA2mSwYiUDPzwtBEJXlUbQ69dSoPJOuYE2-lyzDw8YEnkjIF-iT3lQEh.SSrhmDsIKf6voGrV)
* [Thursday's Recording](https://appstate.zoom.us/rec/share/XePy2e0YE7nbfYWDVZaWhtZyi5XALughz-VtC3dpmruskF1b7ikiY2yftLhSafKI.HePVDauxU0n_S4jg)
-->

***

**Week 9: (Mar 15 - 19)**

* Chapter 4: Bivariate Distributions (4.2, 4.3)
* In Class Quiz 07 (Thursday, last 20 min of class)
* [Homework 9: Due Friday Oct 223rd](Homework.html)

*Lecture Recordings:*
<!--
* [Tuesday's Recording](https://appstate.zoom.us/rec/share/ZSDWWLdGWEZnSz6i2XiuxzsxYj9gpwQMQlEvDdMTmh52V3dM8uG8GyGT709cBjFJ.CGuFT8hScb-nGbkg)
* [Wednesday's Recording](https://appstate.zoom.us/rec/share/LrkIq-RkafgQbCDhJFeXZASzIlO4gvnw_ah3-EYOxYiQhD5e7WUP4FciTeiRAwjR.WCsbHBgqhrS3Azo7)
* [Thursday's Recording](https://appstate.zoom.us/rec/share/DleB0txRNarMat0qpvfgYCYaYd53Q0TSGrFiCFqlPD0fU9g8qpOVQ5tVuCmKurjk.v5BIWtIAXaWnExG1)
-->

***

**Week 10: (Mar 22 --  26)**

* Chapter 4: Bivariate Distributions (4.4)
* In Class Quiz 09 (Thursday, last 20 min of class)
* [Homework 10: Due October 30th](Homework.html)

*Lecture Recordings:*
<!--
* [Tuesday's Recording](https://appstate.zoom.us/rec/share/mwDTGPGoFIINgmYNXK_fLo8RAXbW1WTEZGUV4Qliwr-KtXFnnP4FyRi_AZooGOUK.2ho1q_whXKvuhtm4)
* [Wednesday's Recording](https://appstate.zoom.us/rec/share/BwexTFqlveuZ1-iQaH8F5BcGAdQKr9jkI5PbUYyzXbhH75yvfoNlJ6CKe9sOtQY.n4SgA1n99ygtLWHv)
* [Thursday's Recording](https://appstate.zoom.us/rec/share/qmCcz3Y45_LEHszbI5layXIoz6UXfJAqMwJQOJkTTXbV0bnKfpzfskPVL1AflWOJ.U53U17ORBvh5WJaK)

-->

***

**Week 11: (Mar 29 -- Apr 02)**

* Chapter 5: Distributions of Functions of Random Variables (5.1, 5.2, 5.3)
* In Class Quiz 10 (Thursday, last 20 min of class)
* Review for exam 2

*Lecture Recordings:*
<!--
* [Tuesday's Recording](https://appstate.zoom.us/rec/share/y2k9RzPFA1d_SqwWFdkctvDsSzUchqH7DYteDPJhN89fR754zOkDMWeG31z5X0f5.cbe8Qt5dlPG4u_kS)
* [Wednesday's Recording](https://appstate.zoom.us/rec/share/MIzWvHlT57qeCLFNjpuTZmXA8ZW6UsLLkDRtN9V42B0-DEIZMojeo7Bh2BA-nPsB.M1ONOVBZAblyBBz2)
* [Thursday's Recording](https://appstate.zoom.us/rec/share/3H1J-XY3xkJ40AlbM4uAJEQ3BCt-cVFoi9WRiKqbKs0mj3zsvcXMz3lSVFW-Xh-E.IAsp8lBVssHiwjh7)
-->

***

**Week 12: (Apr 05 --  09)**

* *Test 02: Thursday the 5th of Nov. Covers Ch 3 and Ch4.*
* Chapter 5: Distributions of Functions of Random Variables (5.4)

*Lecture Recordings:*
<!--
* [Tuesday's Recording](https://appstate.zoom.us/rec/share/4P6rVfaRKW9dqgxvGtHsTim-7m6LeeeeD9SmEn0AL01UfPjfkxUFf4NcOhvdNB76.eUwiPaoVk8bBEZO7)
* [Wednesday's Recording 1](https://appstate.zoom.us/rec/share/F2kRrKezb7nbBaKPRNpAknqbowdDrZfxsOGPYh4uBPaqcD5Kgw8csfrqKuy3wxI1.w3rOaK1Rn3EQMCdj) - Exam 2 Review
* [Wednesday's Recording 2](https://appstate.zoom.us/rec/share/9zqXeqShLFeujVVWLMll9om8aRIVCSYZO09JFpQ4ir9lmIPdtkbw3MUtEi1F_AgL.ggk-K4R5FyokaE9V) - Exam 2 Extra Review
* [Thursday's Recording]() - Exam 2, No recording
-->

***

**Week 13: (Apr 12 --  16)**

* [Exam 2 grades distribution](exam2grades.html) 

* Chapter 5: Distributions of Functions of Random Variables (5.5, 5.6)
* In Class Quiz 11 (Thursday, last 20 min of class)
* [Practice problems for Q11 ](Homework.html)

*Lecture Recordings:*
<!--
* [Tuesday's Recording]() - No class/recording (Thanks! Spectrum Internet..)
* [Wednesday's Recording](https://appstate.zoom.us/rec/share/1Ml-pc5O-He45EW_fSsNeahUO-3r-ZFhVdrU6ARd49GpiUKe5G1yNv_FDyup4Oba.dX_jxuCvKcXdbz2u) 
* [Thursday's Recording](https://appstate.zoom.us/rec/share/VH92xmiWuWMOcCI9OmGWwIBWaG67zQhgi9SifUwPknPOVp6uEmuBDqNx6VWngUE_.vyPpeJCy9LOqMtyU) 
-->

***

**Week 14: (Apr 19 --  23)**

* Chapter 5: Distributions of Functions of Random Variables (5.7, 6.3)
* In Class Quiz 12 (Thursday, last 20 min of class)
* [Practice problems for Q12 ](Homework.html)

*Lecture Recordings:*
<!--
* [Tuesday's Recording](https://appstate.zoom.us/rec/share/HKmUzAsYvpnlILSJbaLwrqU1jveM2LO7amp3H1fPJpuF-ZhfYXvJBK4VTR2iHJdt.IPIDg7VNgiLfEsyG) 
* [Wednesday's Recording](https://appstate.zoom.us/rec/share/JyeVCdsRBW2F6D_xUH4TF7EOFArfqee5SKyek4V0TpnYVvtNTEBeIWEVqFayBY8.P6RUR2N4LWxeaMt1)
* [Thursday's Recording](https://appstate.zoom.us/rec/share/HYRd0yOZjZzhDXFiXmXjs7WYK4gQYB1aLzq82_LGDNUI4-Xk7V6biF8LYx-S5agp.-nv--LPXEpcJGphX) 
-->



***

**Week 15: (Apr 26 -- 29)**


* Review for final

***

**Final Exam**

* TBA

***

